### PR TITLE
MING - add leading zero since our new eslint is also with leading zero (consistency! yay! ) and add the new rules created from 8.2.0 to 9.3.0

### PR DESCRIPTION
**Pull request by roubaobaozi**

### CODE REVIEW

**Review by darrennolan — APPROVED** [review]
Though curious why our SASS rules now diff to our styled-components rule.

**Comment by roubaobaozi** [comment]
Should we go through and update sass linting too? Because we don’t use it anymore .. do upstairs?

**Comment by darrennolan** [comment]
Mmmm hawk does, doesn't it?

Would not suggest changing anything for upstairs.

More just a point of curiosity that were changing, than anything else.

**Comment by roubaobaozi** [comment]
It does but we’re pretty far from latest release 😂

**Comment by roubaobaozi** [comment]
hi @seankoji can you weigh in? You set the original eslint rule 1 year ago to make “no leading 0” an error for JS:

```
6faea723     seankoji, a year ago   (January 5th, 2017 11:00am)
"no-floating-decimal": "error",
```

But our CSS linting has traditionally always errored if there _was_ a leading zero. I want to standardise it, especially with styled-components, because this:

```
opacity: 0.7; // stylelint says uhoh leading zero
background-color: ${rgba(blackPerl, .7)}; // eslint says uhoh no leading zero
```

Will trigger stylelint’s number-leading-zero error on opacity. The 0.7 in background-color’s ${rgba()} is governed by the eslint rules, which says no-floating-decimal will error (so .7 would error there.)

screen shot 2018-06-20 at 14 42 38

**Review by seankoji — APPROVED** [review]
looks good. leading zeros was more just around standardisation rather than any technical reason

**Review by nirajaryal — APPROVED** [review]

**Review by steve-taylor — APPROVED** [review]

**Pull request merged**
